### ISSUE TITLE
Latest pyarmor : not working with restrict mode ?

### ISSUE THREAD

**Issue by Lk4rma** [venaxyt/mysterium#10]
Hello,

I'm using latest pyarmor from pip (PyArmor Trial Version 7.0.3):
When using the zip (containing pyarmor obfuscated script and pytransform directory) mysterium keep having the error :
ModuleNotFoundError: No module named 'pytransform' 

(Although it correctly copy theses file under modules directory)

I tried to fool it, creating the pytransform directory at the mysterium root, and using mysterium directly on the python file, but then I had a "Restrict mode error".

I think latest pyarmor use by default a "restrict mode = 1" (see : https://pyarmor.readthedocs.io/en/latest/mode.html#restrict-mode ).
It check if the obfuscated script is modified or is called from a non obfuscated script it- and raise the error : "Check bootstrap restrict mode failed" at execution.

I haven't found any workaround so far.

Anyone having the same issue ?

**Comment by venaxyt** [comment]
Hey bro, you have to try without Mysterium, by choosing n at the beggining for decline Blue Mysterium.
