### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by CarryLambo** [venaxyt/mysterium#11]
File "C:\Users\Carry\Desktop\mysterium-main\modules\blue.py", line 173, in execute_file
    exec(self.content, globals(), self.variables)
  File "<string>", line 3, in <module>
ModuleNotFoundError: No module named 'pytransform'

**Comment by Slimakoi** [comment]
You need to have the folder named `pytransform` in the same path as the script you want the deobfuscate

**Comment by venaxyt** [comment]
Exact, you have to falsificate the Pyarmor's architecture by creating a pytransform folder, dropping the _pytransform.dll file in, and also putting in a random `__init__.py` made with Pyarmor.
