### ISSUE TITLE
VERY Unsecure... executes the virus...

### ISSUE THREAD

**Issue by billythegoat356** [venaxyt/mysterium#13]
The idea of this tool is ngl pretty good... but you can easily get a virus with Mysterium.
Mysterium will execute the virus just by creating additionnal libraries, but if the file (virus) uses another libs, or works in a different way, your computer could get infected.

**Comment by venaxyt** [comment]
Yes, this is totally true, everybody who read the code can see it, that's why I always say in the discord server that it could be dangerous and to use Mysterium for unknown files in a virtual machine.
