### ISSUE TITLE
Why doesn't it output the source code?

### ISSUE THREAD

**Issue by DimaTverdoy** [venaxyt/mysterium#15]
I did everything as in the guide (), but when I start mysterium.py, it just executes the script, but does not output the code.
mysterium output:
 ```
[>] Enter uninspected file path : C:\Users\katy\Desktop\mysterium\FINAL_VIRUS.zip
  [>] Enter Python obfuscated file name with extension : C:\Users\katy\Desktop\mysterium\modules\FINAL_VIRUS\virus.pyc

3.9.6 (tags/v3.9.6:db3ff76, Jun 28 2021, 15:26:21) [MSC v.1929 64 bit (AMD64)]

  [>] The code is finished, don't forget to follow @venaxyt / @IDRALOU / @Bleu-No / @vjousse on Github
```
source virus.py:
```
import sys

def print_ver(version):
	print(version)

x = sys.version
print_ver(x)
```

**Comment by venaxyt** [comment]
This is because there is nothing that Mysterium can extract from here, no modules imported apart from sys module which is native, so not in /modules folder.
From this specific code, you cannot extract anything unfortunately.
