### ISSUE TITLE
Error after deleting re.py

### ISSUE THREAD

**Issue by Oberonskiiv2** [venaxyt/mysterium#16]
Hello!
After deleting re.py, I get the following error:

import random
import json
import requests
Traceback (most recent call last):
File "<C:\Users\Administrator\Desktop\mysterium-main\modules\main.py>", line 3, in
File "", line 6, in
ImportError: cannot import name 'randint' from 'random' (C:\Users\Administrator\Desktop\mysterium-main\modules\random.py)

How can I fix this?

**Comment by venaxyt** [comment]
Hey, just delete random.py too from /modules folder.
Sorry for responding so late, I didn't see your issue 😅.
