### ISSUE TITLE
Help in decompiling pyarmor

### ISSUE THREAD

**Issue by Naster1202** [venaxyt/mysterium#19]
Hello friend, could you help me with decompiling the encrypted python file,
The problem is that there is a Python project, but it is encrypted using Pyarmor,
The source code is there and everything adjacent to it too
Thanks in advance

**Comment by Naster1202** [comment]
I don't understand, I upload the zip archive to the folder with mystremia and select the same zip archive in the script as indicated in the instructions and then specify the name of the python file. what do i get any error

**Comment by Naster1202** [comment]
![image](https://user-images.githubusercontent.com/62520991/151179894-dd96e89d-8f78-4744-92c3-e75048478012.png)

**Comment by venaxyt** [comment]
Hey bro, after dropping the zip file in, you have to enter the name of your python main script file, for you, I suppose it is heart.py like I'm seeing in your screenshot. After that it will work, if you want there is also a very detailed tutorial in the documentation of the project.

**Comment by APPxPY** [comment]
> ![image](https://user-images.githubusercontent.com/62520991/151180104-96e9aa06-c816-4701-9793-19160750186e.png)
> 
> ![image](https://user-images.githubusercontent.com/62520991/151180240-8ebd537c-49e1-4b02-896b-632e73eb8f41.png)

Привет земляк) Получилось расшифровать? Я пытаюсь но что-то не выходит, если что, тоже хочу код этой штуки с сердечком глянуть)

**Comment by venaxyt** [comment]
Привет дорогой друг, проблема на самом деле решается просто, я уже объяснял ее тебе в своем прошлом сообщении, просто введи в консоль основной файл, т. последний доступен в документации по ссылке на YouTube
