### ISSUE TITLE
TypeError: 'str' object is not callable

### ISSUE THREAD

**Issue by h20003** [venaxyt/mysterium#20]
getting error.

TypeError: 'str' object is not callable

**Comment by h20003** [comment]
pyarmor version 7.03
compiled python version 3.9.6
local python version 3.9.5

**Comment by venaxyt** [comment]
Probably due to useless call of re.py module, you have to delete re.py from ./modules folder.

**Comment by h20003** [comment]
same error after deleting re.py file from modules folder.

**Comment by venaxyt** [comment]
I need more pecision about the error, it would be better for you to join the Discord server in the documentation.
