### ISSUE TITLE
unsucessful in deobfuscating pyarmor obfuscation.

### ISSUE THREAD

**Issue by vaibhav-rbs** [venaxyt/mysterium#21]
deobfuscate.zip contains my obfuscated app code in zip format
`pyarmor==7.3.6`
```
$ uname -a
Darwin
 ```

  [>] Enter uninspected file path : /Users/username/app-code/mysterium/deobfuscate.zip
  [>] Enter Python obfuscated file name with extension : deobfuscate/__init__.py

Traceback (most recent call last):
  File "modules/deobfuscate/__init__.py", line 1, in <module>
    from .pytransform import pyarmor_runtime
ModuleNotFoundError: No module named '__main__.pytransform'; '__main__' is not a package

obfuscated __init__.py

```
from .pytransform import pyarmor_runtime
pyarmor_runtime()
__pyarmor__(__name__, __file__, b'\x50\x59\x4ca....', 2)
```

source __init__.py

```
__version__ = '1.0.0.0'
```

**Comment by venaxyt** [comment]
Hey bro, you onle have to put init.py here
[>] Enter Python obfuscated file name with extension : init.py
That's why it doesn't work.
Sorry for the late response I was not here.
