### ISSUE TITLE
NameError: name '__pyarmor__' is not defined

### ISSUE THREAD

**Issue by eliasto** [venaxyt/mysterium#22]
Hello! When I run the script I get this error: `NameError: name '__pyarmor__' is not defined`
There is my zip file:
[dist.zip](https://github.com/venaxyt/mysterium/files/8234900/dist.zip)

Thank you! :)

**Comment by venaxyt** [comment]
Sad times the tutorial has been deleted from YouTube, I will reupload it somewhere and send you so you will be able to understand x)
