### ISSUE TITLE
'str' object has no attribute 'match'

### ISSUE THREAD

**Issue by ddrm86** [venaxyt/mysterium#26]
Hello.
Does mysterium work with new PyArmor versions?
I just tried some obfuscated code that runs fine on Windows 10 64-bit and Python 3.8.6, but when I pass it through Mysterium the output is:

```
import re
import re
re.escape(w)
re.escape(i)
re.escape(n)
re.escape(d)
re.escape(o)
re.escape(w)
re.escape(s)
'str' object has no attribute 'match'

 [>] The code is finished, don't forget to follow @venaxyt / @IDRALOU / @Bleu-No / @vjousse on Github
```

**Comment by novakdwy** [comment]
As said ~10000 times on his Discord, just remove re.py from ./modules folder and try again.

**Comment by venaxyt** [comment]
As you said, I answered to this issue approximately a million times, so thanks for doing the job for me this time.

> As said ~10000 times on his Discord, just remove re.py from ./modules folder and try again.
