### ISSUE TITLE
Failed to deobfuscate

### ISSUE THREAD

**Issue by ImJoke** [venaxyt/mysterium#39]
So I tried to deobfuscate this file [Brute-FB](https://raw.githubusercontent.com/Yusep-XD/Brute-FB/main/Brute-FB.py "Maybe a virus, IDK") but failed

<img width="533" alt="image" src="https://github.com/venaxyt/mysterium/assets/55929550/04292d58-e919-499c-a02b-24c2b504d666">

**Comment by venaxyt** [comment]
Delete re.py from /modules folder and try again.
Sorry for the late response, I'm not here often.
