### ISSUE TITLE
Don't contact his scam telegram

### ISSUE THREAD

**Issue by Ayko69** [venaxyt/mysterium#40]
He will say to pay him first without proving anything under an excuse of don't waste his time
i said if he not gonna show even a single photo of it working i won't pay 
so he didn't dare to do it and say i am just not gonna pay lol 
next day found he deleted some  messages to make it look like he's the good one in the conversation lol 
then i just decided to delete everything so he don't use it on another victim 

Take care !

**Comment by Ayko69** [comment]
what ever you repspond or say you will saty a scum don't worry lol

**Comment by venaxyt** [comment]
This man actually never bought anything to me.
And I never scammed anyone, I have thousands of proofs if needed.
So have a good day, go to waste your time with somebody other.
