### ISSUE TITLE
RuntimeError: Bad magic number in .pyc file

### ISSUE THREAD

**Issue by etxnight** [venaxyt/mysterium#43]
the whole:

  [>] Enter uninspected file path : C:\Users\paulr\Downloads\DECOMPILEMAINL\Silence.pyc

RuntimeError: Bad magic number in .pyc file

  [>] The code is finished
  
  
it was a .pyc file and in pycdc it says
# WARNING: Decompyle incomplete

**Comment by venaxyt** [comment]
You have to decompile your original file with the right version of Python.
As example to fix that, use pyinstxtractor on your executable file.
In the logs, you'll have the Python version used to compile the original code.
Then, install this version on your computer if you don't already have it, and do the same thing but executing it with this version, it will give you uncorrupted files.
(ex: py -3.9 pyinstxtractor file.exe)
