### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by eyal9** [venaxyt/mysterium#5]
What if i don't have the _pytransform.dll and __init__ files? The code I have was an exe and I uncompylied it so i have the source code, but the source is protected with pyarmor on top of the exe. So I'm left with the pyarmor code. Is it possible to get the real source now?

**Comment by venaxyt** [comment]
Yes with no problem, you can extract from here it's memory (variables / dict / list....) and the functions like module ones and print and some other functions. To do this you can go to watch my tutorial on YouTube, which is in the documentation.
To do that, you have to put in a zip folder the file.py and the pytransform folder, and you drop in mysterium this zip file, and you finally have to input the main py name without it's extension.
