### ISSUE TITLE
'str' object has no attribute 'match'

### ISSUE THREAD

**Issue by Nqndi** [venaxyt/mysterium#7]
Hi!
When I try to "reverse" a file with the program, this comes up:
![kép](https://user-images.githubusercontent.com/73391505/140827461-67de2836-c024-4663-ba5c-629c2ecb5b81.png)

**Comment by rifkymcz** [comment]
delete re.py from /modules directory

**Comment by Nqndi** [comment]
works, thanks!

**Comment by Oberonskiiv2** [comment]
Hello!
After deleting re.py, I get the following error:
