### ISSUE TITLE
'str' object has no attribute 'match'

### ISSUE THREAD

**Issue by DZ0Jeff** [venaxyt/mysterium#9]
Hi,

when I enter the file path to pyarmor obfuscate ".zip", the following error appears:

`import re
import re
re.escape(w)
re.escape(i)
re.escape(n)
re.escape(d)
re.escape(o)
re.escape(w)
re.escape(s)
'str' object has no attribute 'match'
`

**Comment by venaxyt** [comment]
Hey bro, the re module is unstable, if you want you can try to fix it, but if you only want to get your program not stopping because of this, just delete re.py from /modules folder.
